name: Install SuperCollider
description: Install SuperCollider
inputs:
  branch:
    description: SuperCollider branch
    required: false
    default: develop
  origin:
    description: SuperCollider repo origin
    required: false
    default: https://github.com/supercollider/supercollider.git
runs:
  using: "composite"
  steps:
    - name: Clone SuperCollider
      run: |
        git clone --quiet --recursive --branch ${{ inputs.branch }} ${{ inputs.origin }} /tmp/supercollider
        cd /tmp/supercollider
        mkdir build
        echo "SC_COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
        if [ "$RUNNER_OS" == "Linux" ]; then
          echo "SC_ORIGIN_MD5=$(echo ${{inputs.origin}} | md5sum | head -c 7)" >> $GITHUB_ENV
        elif [ "$RUNNER_OS" == "macOS" ]; then
          echo "SC_ORIGIN_MD5=$(echo ${{inputs.origin}} | md5 | head -c 7)" >> $GITHUB_ENV
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash
    - name: Cache SuperCollider
      id: cache
      uses: actions/cache@v3
      with:
        path: /tmp/supercollider/build
        key: ${{ runner.os }}-supercollider-${{ env.SC_ORIGIN_MD5 }}-${{ env.SC_COMMIT_SHA }}
        restore-keys: |
          ${{ runner.os }}-supercollider-
    - name: Validate cache
      run: echo "Cached? ${{ steps.cache.outputs.cache-hit }}"
      shell: bash
    - name: Install SuperCollider Deps
      run: |
        echo "Installing SuperCollider deps..."
        if [ "$RUNNER_OS" == "Linux" ]; then
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update --yes
          sudo apt-get install --yes \
            alsa-oss \
            alsa-utils \
            build-essential \
            cmake \
            jackd2 \
            libasound2-dev \
            libavahi-client-dev \
            libfftw3-dev \
            libicu-dev \
            libjack-jackd2-dev \
            libreadline6-dev \
            libsndfile1-dev \
            libudev-dev \
            libxt-dev \
            pkg-config
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install \
            cmake \
            fftw \
            git \
            jack \
            libsndfile \
            portaudio \
            qt5 \
            readline
          ldconfig
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash
    - name: Prep SuperCollider build
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        echo "[Cache Miss] Configuring SuperCollider..."
        if [ "$RUNNER_OS" == "Linux" ]; then
          cmake \
            --debug-output \
            -DCMAKE_build_TYPE=Release \
            -DSC_EL=OFF \
            -DSC_IDE=OFF \
            -DSC_QT=OFF \
            -DSUPERNOVA=ON \
            /tmp/supercollider
        elif [ "$RUNNER_OS" == "macOS" ]; then
          cmake \
            -DCMAKE_PREFIX_PATH=`brew --prefix qt5` \
            -DSUPERNOVA=ON \
            -G Xcode \
            /tmp/supercollider
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash
      working-directory: /tmp/supercollider/build
    - name: Build SuperCollider
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        echo "[Cache Miss] Building SuperCollider..."
        if [ "$RUNNER_OS" == "Linux" ]; then
          make
        elif [ "$RUNNER_OS" == "macOS" ]; then
          cmake --build . --target install --config RelWithDebInfo
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash
      working-directory: /tmp/supercollider/build
    - name: Install SuperCollider
      run: |
        echo "Installing SuperCollider..."
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo make install/fast
          mkdir -p /home/runner/.local/share/SuperCollider/synthdefs
        elif [ "$RUNNER_OS" == "macOS" ]; then
          echo "PATH=/tmp/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/MacOS:/tmp/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/Resources/:$PATH" >> $GITHUB_ENV
          mkdir -p "/Users/runner/Library/Application Support/SuperCollider/synthdefs"
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash
      working-directory: /tmp/supercollider/build
    - name: Setup Jack
      run: |
        echo "Setting up Jack..."
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo usermod -a -G audio ${USER}
        fi
        sleep 1
        sudo -E su ${USER} -c "jackd -r -ddummy -r44100 -p1024" &
        sleep 1
      shell: bash
    - name: Sanity-check scsynth
      run: |
        echo "Sanity-checking scsynth..."
        scsynth -v
        scsynth -h || true
        sudo -E su ${USER} -c "scsynth -D 0 -H default\:snchk -R 0 -u 57110" &
        sleep 5
        killall scsynth
      shell: bash
    - name: Sanity-check supernova
      run: |
        echo "Sanity-checking supernova..."
        supernova -v
        supernova -h || true
        sudo -E su ${USER} -c "supernova -D 0 -H default\:snchk -R 0 -u 57110" &
        sleep 5
        killall supernova
      shell: bash
    
